### ISSUE TITLE
Make file broken paths - SOLVED

### ISSUE THREAD

**Issue by IvRRimum** [commonsearch/cosr-ops#17]
When you call for example:

`make aws_elasticsearch_template`

I got the error:

```
root@bestbotsforcrawl:~/commonsearch/cosr-ops# make aws_elasticsearch_template
python aws/cloudformation/template-elasticsearch.py --pretty
Traceback (most recent call last):
  File "aws/cloudformation/template-elasticsearch.py", line 14, in <module>
    from common import MAPPINGS, get_auto_scaling_group, get_launch_configuration
  File "/root/commonsearch/cosr-ops/aws/cloudformation/common.py", line 6, in <module>
    from jinja2 import Template
ImportError: No module named jinja2
make: *** [aws_elasticsearch_template] Error 1
```

I investigated the error and it seems, the make file uses the system's python version, instead of virtualenv's python( and its packages ).

So i opened makefile and edited the code.

before(gives error):

```
# View the CloudFormation template
aws_elasticsearch_template:
        python aws/cloudformation/template-elasticsearch.py --pretty 
```

After(working fine and acctualy shows the template):

```
# View the CloudFormation template
aws_elasticsearch_template:
        venv/bin/python aws/cloudformation/template-elasticsearch.py --pretty
```

Am i doing something wrong, or is this an issue ?

**Comment by IvRRimum** [comment]
Should i fix the make file and make a pull request ?

**Comment by IvRRimum** [comment]
also same for aws commands:

before(fails):

```
# Validate the CloudFormation template
aws_elasticsearch_validate: aws_elasticsearch_build
        template=$$(cat /tmp/cloudformation-elasticsearch-template.json) ;\
        aws cloudformation validate-template --template-body "$$template"
```

after(works):

```
# Validate the CloudFormation template
aws_elasticsearch_validate: aws_elasticsearch_build
        template=$$(cat /tmp/cloudformation-elasticsearch-template.json) ;\
        venv/bin/aws cloudformation validate-template --template-body "$$template"
```

**Comment by IvRRimum** [comment]
Nvm, its be being dumb.

I needed to define source:
`source venv/bin/activate`

Works excelent now!
